[project]
name = "arabic-legal-document-qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dvc>=3.67.1",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "pypdf>=6.16.2",
    "uvicorn>=0.52.4",
]

[project.scripts]
arabic-legal-document-qa = "arabic_legal_document_qa:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
