import torch
import logging
from typing import List, Optional
from ..LLMEnums import QwenEnums, DocumentTypeEnum
from ..LLMInterface import LLMInterface
from transformers import AutoModelForCausalLM, AutoTokenizer
from sentence_transformers import SentenceTransformer

logger = logging.getLogger(__name__)

class QwenProvider(LLMInterface):
    """
    Qwen-based implementation of the LLM provider interface.

    This provider supports both causal language generation and text
    embeddings using Hugging Face Transformers and Sentence Transformers.

    Attributes:
        device: Device used for model inference, typically ``"cuda"`` or
            ``"cpu"``.
        dtype: PyTorch data type used by the models.
        generation_model_id: Identifier of the loaded generation model.
        generation_model: Loaded causal language model.
        generation_tokenizer: Tokenizer associated with the generation model.
        embedding_model_id: Identifier of the loaded embedding model.
        embedding_model: Loaded Sentence Transformer embedding model.
        embedding_size: Dimension of the generated embedding vectors.
        default_input_max_characters: Maximum number of input characters
            processed from a prompt or text.
        default_generation_max_output_tokens: Default maximum number of
            tokens generated per request.
        default_generation_temperature: Default sampling temperature.
        enable_thinking: Whether Qwen's internal thinking mode is enabled.
    """
    def __init__(
        self, 
        device: str = None,
        default_input_max_characters: int = 3000,
        default_generation_max_output_tokens: int = 1024,
        default_generation_temperature: float = 0.3,
        enable_thinking: bool = False,
    ):
        """
        Initialize the Qwen provider.

        Args:
            device: Device on which models should run. If ``None``, CUDA is
                used when available; otherwise CPU is selected.
            default_input_max_characters: Maximum number of characters
                accepted from an input text.
            default_generation_max_output_tokens: Default maximum number of
                tokens generated by the language model.
            default_generation_temperature: Default generation temperature.
                Higher values produce more varied output.
            enable_thinking: Enable Qwen's internal thinking mode when
                applying the chat template.
        """

        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.dtype = torch.bfloat16 if self.device == "cuda" else torch.float32
 
        self.generation_model_id: Optional[str] = None
        self.generation_model = None
        self.generation_tokenizer = None
        
        # Embedding model 
        self.embedding_model_id: Optional[str] = None
        self.embedding_model = None
        self.embedding_size: Optional[int] = None

        self.default_input_max_characters = default_input_max_characters
        self.default_generation_max_output_tokens = default_generation_max_output_tokens
        self.default_generation_temperature = default_generation_temperature
 
        # Qwen3 supports an internal "thinking" mode via the chat template.
        # Off by default for RAG (lower latency, more predictable output);
        self.enable_thinking = enable_thinking
        
    def set_generation_model(self, model_id: str):
        """
        Load the Qwen causal language model and its tokenizer.

        Args:
            model_id: Hugging Face model identifier for the generation
                model.

        Raises:
            Exception: If the model or tokenizer cannot be loaded.
        """

        self.generation_model_id = model_id
        self.generation_tokenizer = AutoTokenizer.from_pretrained(self.generation_model_id)
        self.generation_model = AutoModelForCausalLM.from_pretrained(
            self.generation_model_id,
            torch_dtype=self.dtype,
            device_map="auto" if self.device == "cuda" else None,   
        )
        
        if self.device != "cuda":
            self.generation_model.to(self.device)

        self.generation_model.eval()
        logger.info(f"Loaded generation model: {model_id} on {self.device}")
        
    def set_embedding_model(self, model_id: str, embedding_size: int):
        """
        Load and configure the Qwen embedding model.

        Args:
            model_id: Hugging Face model identifier for the embedding model.
            embedding_size: Desired dimensionality of the output embeddings.
                The model output is truncated to this dimension.

        Raises:
            Exception: If the embedding model cannot be loaded.
        """

        self.embedding_model_id = model_id
        self.embedding_size = embedding_size

        self.embedding_model = SentenceTransformer(
            self.embedding_model_id,
            device=self.device,
            model_kwargs={"torch_dtype": self.dtype},
            tokenizer_kwargs={"padding_side": "left"},  # required for Qwen3-Embedding's last-token pooling
            truncate_dim=self.embedding_size,  
        )

        logger.info(f"Loaded embedding model: {model_id} (dim={embedding_size}) on {self.device}")
         
    def process_text(self, text: str) -> str:
        """
        Truncate and normalize input text.

        Args:
            text: Input text to process.

        Returns:
            The input text truncated to the configured maximum character
            length with leading and trailing whitespace removed.
        """
        return text[: self.default_input_max_characters].strip()

    def construct_prompt(self, prompt: str, role: str):
        """
        Construct a chat message for the Qwen chat template.

        Args:
            prompt: Message content.
            role: Role of the message, such as ``"system"``, ``"user"``,
                or ``"assistant"``.

        Returns:
            A dictionary containing ``role`` and processed ``content``.
        """
        return {"role": role, "content": self.process_text(prompt)}

    def generate_text(self, prompt: str, chat_history: list = [], max_output_tokens: int= None,
                      temp: float = None):
        """
        Generate a response using the configured Qwen language model.

        Args:
            prompt: User prompt to process and send to the model.
            chat_history: Optional previous conversation messages. Each
                message must contain ``role`` and ``content`` fields.
            max_output_tokens: Maximum number of tokens to generate. If
                omitted, ``default_generation_max_output_tokens`` is used.
            temp: Sampling temperature. If omitted,
                ``default_generation_temperature`` is used. Values greater
                than zero enable sampling.

        Returns:
            The generated response as a string, or ``None`` if the
            generation model or tokenizer has not been configured.
        """

        if self.generation_model is None or self.generation_tokenizer is None:
            logger.error("Generation model was not set. Call set_generation_model first.")
            return None

        max_output_tokens = max_output_tokens or self.default_generation_max_output_tokens
        temp = self.default_generation_temperature if temp is None else temp

        messages = list(chat_history) + [self.construct_prompt(self.process_text(prompt), role="user")]

        text_input = self.generation_tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=self.enable_thinking,
        )
        
        model_inputs = self.generation_tokenizer([text_input], return_tensors="pt").to(self.generation_model.device)

        generate_kwargs = dict(
            **model_inputs,
            max_new_tokens=max_output_tokens,
        )

        if temp and temp > 0:
            generate_kwargs.update(do_sample=True, temperature=temp, top_p=0.8, top_k=20)
        else:
            generate_kwargs.update(do_sample=False)

        with torch.no_grad():
            generated_ids = self.generation_model.generate(**generate_kwargs)

        output_ids = generated_ids[0][len(model_inputs.input_ids[0]):].tolist()

        try:
            think_end_id = self.generation_tokenizer.convert_tokens_to_ids("</think>")
            split_at = len(output_ids) - output_ids[::-1].index(think_end_id)
        except ValueError:
            split_at = 0

        response = self.generation_tokenizer.decode(output_ids[split_at:], skip_special_tokens=True).strip()
        return response

    def embed_text(self, text: str, document_type: str = None):
        """
        Generate a normalized embedding vector for the provided text.

        Args:
            text: Text to encode into an embedding vector.
            document_type: Type of text being embedded. If it matches
                ``DocumentTypeEnum.QUERY.value``, the query-specific
                embedding prompt is used. Other values are treated as
                passage/document text.

        Returns:
            A normalized embedding vector represented as a list of floats,
            or ``None`` if the embedding model has not been configured.
        """
        
        if self.embedding_model is None:
            logger.error("Embedding model was not set. Call set_embedding_model first.")
            return None

        text = self.process_text(text)

        prompt_name = DocumentTypeEnum.QUERY.value if document_type == DocumentTypeEnum.QUERY.value else None

        embedding = self.embedding_model.encode(
            [text],
            prompt_name=prompt_name,
            normalize_embeddings=True,
        )
        return embedding[0].tolist()